<?php require_once __DIR__ . '/includes/bootstrap.php'; $layoutOptions = ['active' => 'patents']; ?>
<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>专利与知识产权 - 甘肃骐霖智能装备</title><meta name="description" content="展示胶囊生产线相关实用新型专利证书、核心结构与公开信息。"><link rel="canonical" href="https://www.gsqilin.cn/patents.php"><link rel="stylesheet" href="styles/main.css?v=20260901-4"><link rel="stylesheet" href="styles/patents.css?v=20260901-1"></head><body data-page="patents"><?php include __DIR__ . '/includes/header.php'; ?><main>
<section class="patent-hero"><div class="container patent-hero-grid"><div><span class="eyebrow">知识产权</span><h1>专利成果与工程创新</h1><p>围绕硬质空心胶囊生产线、脱模、定长、切口与套合等关键工序，持续积累可用于设备设计和工程交付的技术成果。</p><div class="patent-stats"><div><strong>7 项</strong><span>页面已收录专利</span></div><div><strong>实用新型</strong><span>专利类型</span></div><div><strong>专利权有效</strong><span>新增登记簿所载状态</span></div></div></div><figure><img src="images/patents/capsule-line-certificate.jpg" alt="一种胶囊生产线实用新型专利证书"></figure></div></section>
<section class="patent-detail section-pad"><div class="container"><div class="section-heading"><span class="eyebrow">已收录专利</span><h2>一种胶囊生产线</h2><p>以下内容根据现有专利证书及公开文本整理。法律状态及权利归属如需用于商务或法律文件，请以国家知识产权局最新登记为准。</p></div><div class="patent-info-grid"><article><span>专利类型</span><strong>实用新型专利</strong></article><article><span>专利号</span><strong>ZL 2014 2 0122072.9</strong></article><article><span>申请日</span><strong>2014年3月18日</strong></article><article><span>授权公告号</span><strong>CN 204038547 U</strong></article><article><span>证书号</span><strong>第4008541号</strong></article><article><span>技术领域</span><strong>硬质空心胶囊生产线</strong></article></div><div class="patent-summary"><div><h3>技术要点</h3><p>该实用新型涉及多轨道胶囊模条输送结构，通过升降台、横向传送装置与纵向输送轨道协同，使多个模条能够在相同周期内完成转移，从而改善传统单轨输送环节的效率限制。</p></div><ul><li>多轨道传输胶囊模条</li><li>升降台多工位转移</li><li>横向与纵向输送协同</li><li>适用于空心硬质胶囊生产线</li></ul></div></div></section>
<section class="patent-portfolio section-pad"><div class="container"><div class="section-heading"><span class="eyebrow">新增专利登记</span><h2>胶囊生产装备专利组合</h2><p>以下六项根据国家知识产权局专利登记簿副本整理，法律状态以登记机关最新记录为准。</p></div><div class="patent-card-grid">
<article class="patent-card"><a class="patent-cover" href="images/patents/registers/zl-2017-10391833-9.pdf" target="_blank" rel="noopener"><img src="images/patents/registers/zl-2017-10391833-9.jpg" alt="ZL201710391833.9专利登记簿首页"></a><div class="patent-card-body"><span class="status-badge">专利权有效</span><h3>硬质空心胶囊生产用定长套合装置</h3><dl><div><dt>专利号</dt><dd>ZL201710391833.9</dd></div><div><dt>申请日</dt><dd>2017.05.27</dd></div><div><dt>授权日</dt><dd>2023.05.26</dd></div><div><dt>证书号</dt><dd>5997034</dd></div></dl><a class="patent-link" href="images/patents/registers/zl-2017-10391833-9.pdf" target="_blank" rel="noopener">查看登记簿（PDF）</a></div></article>
<article class="patent-card"><a class="patent-cover" href="images/patents/registers/zl-2017-20613983-5.pdf" target="_blank" rel="noopener"><img src="images/patents/registers/zl-2017-20613983-5.jpg" alt="ZL201720613983.5专利登记簿首页"></a><div class="patent-card-body"><span class="status-badge">专利权有效</span><h3>硬质空心胶囊生产用脱模定长切口套合一体机专用机箱</h3><dl><div><dt>专利号</dt><dd>ZL201720613983.5</dd></div><div><dt>申请日</dt><dd>2017.05.27</dd></div><div><dt>授权日</dt><dd>2019.05.03</dd></div><div><dt>证书号</dt><dd>8793566</dd></div></dl><a class="patent-link" href="images/patents/registers/zl-2017-20613983-5.pdf" target="_blank" rel="noopener">查看登记簿（PDF）</a></div></article>
<article class="patent-card"><a class="patent-cover" href="images/patents/registers/zl-2017-20614180-1.pdf" target="_blank" rel="noopener"><img src="images/patents/registers/zl-2017-20614180-1.jpg" alt="ZL201720614180.1专利登记簿首页"></a><div class="patent-card-body"><span class="status-badge">专利权有效</span><h3>一种硬质空心胶囊切口装置</h3><dl><div><dt>专利号</dt><dd>ZL201720614180.1</dd></div><div><dt>申请日</dt><dd>2017.05.27</dd></div><div><dt>授权日</dt><dd>2018.12.25</dd></div><div><dt>证书号</dt><dd>8265107</dd></div></dl><a class="patent-link" href="images/patents/registers/zl-2017-20614180-1.pdf" target="_blank" rel="noopener">查看登记簿（PDF）</a></div></article>
<article class="patent-card"><a class="patent-cover" href="images/patents/registers/zl-2017-20615347-6.pdf" target="_blank" rel="noopener"><img src="images/patents/registers/zl-2017-20615347-6.jpg" alt="ZL201720615347.6专利登记簿首页"></a><div class="patent-card-body"><span class="status-badge">专利权有效</span><h3>硬质空心胶囊生产用脱模定长切口套合一体机</h3><dl><div><dt>专利号</dt><dd>ZL201720615347.6</dd></div><div><dt>申请日</dt><dd>2017.05.27</dd></div><div><dt>授权日</dt><dd>2019.05.03</dd></div><div><dt>证书号</dt><dd>8803704</dd></div></dl><a class="patent-link" href="images/patents/registers/zl-2017-20615347-6.pdf" target="_blank" rel="noopener">查看登记簿（PDF）</a></div></article>
<article class="patent-card"><a class="patent-cover" href="images/patents/registers/zl-2019-20501217-9.pdf" target="_blank" rel="noopener"><img src="images/patents/registers/zl-2019-20501217-9.jpg" alt="ZL201920501217.9专利登记簿首页"></a><div class="patent-card-body"><span class="status-badge">专利权有效</span><h3>一种全自动硬质空心胶囊生产线</h3><dl><div><dt>专利号</dt><dd>ZL201920501217.9</dd></div><div><dt>申请日</dt><dd>2019.04.15</dd></div><div><dt>授权日</dt><dd>2020.05.08</dd></div><div><dt>证书号</dt><dd>10469612</dd></div></dl><a class="patent-link" href="images/patents/registers/zl-2019-20501217-9.pdf" target="_blank" rel="noopener">查看登记簿（PDF）</a></div></article>
<article class="patent-card"><a class="patent-cover" href="images/patents/registers/zl-2019-20501220-0.pdf" target="_blank" rel="noopener"><img src="images/patents/registers/zl-2019-20501220-0.jpg" alt="ZL201920501220.0专利登记簿首页"></a><div class="patent-card-body"><span class="status-badge">专利权有效</span><h3>一种智能型全自动硬质空心胶囊生产线</h3><dl><div><dt>专利号</dt><dd>ZL201920501220.0</dd></div><div><dt>申请日</dt><dd>2019.04.15</dd></div><div><dt>授权日</dt><dd>2020.02.18</dd></div><div><dt>证书号</dt><dd>10075807</dd></div></dl><a class="patent-link" href="images/patents/registers/zl-2019-20501220-0.pdf" target="_blank" rel="noopener">查看登记簿（PDF）</a></div></article>
</div></div></section>
<section class="patent-gallery section-pad"><div class="container"><div class="section-heading"><span class="eyebrow">结构图示</span><h2>专利附图节选</h2><p>点击图片可在新窗口查看原始尺寸。</p></div><div class="patent-gallery-grid"><a href="images/patents/capsule-line-drawing-1.jpg" target="_blank"><img src="images/patents/capsule-line-drawing-1.jpg" alt="胶囊生产线专利附图一"><span>模条转移机构示意</span></a><a href="images/patents/capsule-line-drawing-2.jpg" target="_blank"><img src="images/patents/capsule-line-drawing-2.jpg" alt="胶囊生产线专利附图二"><span>多层输送结构示意</span></a><a href="images/patents/capsule-line-drawing-3.jpg" target="_blank"><img src="images/patents/capsule-line-drawing-3.jpg" alt="胶囊生产线专利附图三"><span>双侧输送结构示意</span></a></div></div></section>
<section class="product-next-step"><div class="container home-inquiry-inner"><div><span class="eyebrow">项目沟通</span><h2>需要了解专利技术如何应用于设备方案？</h2><p>请提供产能、胶囊规格和现场条件，我们将结合实际项目说明可选配置。</p></div><a class="cta-button cta-light" href="contact.php">提交项目需求</a></div></section>
</main><?php include __DIR__ . '/includes/footer.php'; ?><script src="js/main.js"></script></body></html>
