CREATE TABLE IF NOT EXISTS articles (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    category ENUM('tech', 'news', 'policy') NOT NULL DEFAULT 'tech',
    publish_date DATE NOT NULL,
    thumbnail VARCHAR(255) NOT NULL DEFAULT '',
    summary TEXT NULL,
    content MEDIUMTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    company VARCHAR(180) NOT NULL,
    phone VARCHAR(80) NOT NULL,
    email VARCHAR(180) NOT NULL,
    message TEXT NOT NULL,
    submit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
